### ISSUE TITLE
mvnw clean install - issue on pom

### ISSUE THREAD

**Issue by avasseur-pivotal** [Pivotal-Field-Engineering/pcf-ers-demo#5]
Had this below

I fixed the pom.xml with lombock version as below
```

[user@centos62 pcf-ers-demo]$ git diff
diff --git a/pom.xml b/pom.xml
index 850a5a8..5338d3e 100644
--- a/pom.xml
+++ b/pom.xml
@@ -37,6 +37,7 @@
                <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
+                       <version>1.16.8</version>
                </dependency>

```

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.projectlombok:lombok:jar is missing. @ line 37, column 15
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.gopivotal.pcf.sme.ers:pcf-ers-demo1:0.0.1-SNAPSHOT (/home/user/pcf/pcf-ers-demo/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.projectlombok:lombok:jar is missing. @ line 37, column 15
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by rjain-pivotal** [comment]
Same issue, did you submit the pull request for this pom.xml

**Comment by mborges-pivotal** [comment]
I've merged a pull request with an older Lombok version - 1.16.0, instead of 1.16.18. Let me know if that works for you as I sort out the version today. Thanks!

**Comment by mborges-pivotal** [comment]
Now merged the latest lombok version. Thanks
