### ISSUE TITLE
demo scenario for blue green with improved manifest and cf scaleover plugin

### ISSUE THREAD

**Issue by avasseur-pivotal** [Pivotal-Field-Engineering/pcf-ers-demo#6]
I find the demo scenario for blue green not well documented

here is what I did
- edited manifest to have multiple apps and 4 instances and a joint route "attendees"
- edited colors in layout header to have blue for v1 and green for v2 and build v1 and v2

`cf push --no-start`

`cf start attendees1`

- blue green demo screen, start simulation, then using cf CLI scaleover plugin
(https://github.com/krujos/scaleover-plugin)

`cf scaleover attendees1 attendees2 30s`

here is some git diff

```

--- a/src/main/resources/templates/fragments/layout.html
+++ b/src/main/resources/templates/fragments/layout.html
@@ -31,7 +31,7 @@ References:

 <style>
 .navbar.navbar-inverse.navbar-fixed-top {
-       background-color: #3EBF5C;
+       background-color: #3EB0FF;
 }

```
and the manifest.yml that I am using
```

$ more manifest.yml
---
memory: 512MB
instances: 4
buildpack: java_buildpack_offline
services: []
env:
  SPRING_PROFILES_ACTIVE: cloud
applications:
- name: attendees1
  hosts:
    - attendees1
    - attendees
  path: target/pcf-ers-demo1-0.0.1-SNAPSHOT.jar
- name: attendees2
  hosts:
    - attendees2
    - attendees
  path: target/pcf-ers-demo1-0.0.2-SNAPSHOT.jar
```

**Comment by mborges-pivotal** [comment]
Thanks for the feedback! It looks interesting but I'm not sure how the layout change is represented in the blue green simulation since it's an ajax call. In any case, I'll see if we can incorporate your improvements to the test.

**Comment by avasseur-pivotal** [comment]
Thanks for the merge of the pull request ! Let's close this
